name: nodejs ci
on: push
description: workflow to build and test nodejs application
jobs:
  name: NodeJS Workflow
  build:
    runs-on: ubuntu-latest
    name: Build NodeJS
    steps:
      - uses: actions/checkout@v4
      - name: Use NodeJS
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'
      - run: npm install
      - run: npm test
      